# Generated by Django 3.1.1 on 2022-02-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_cuisine', models.CharField(max_length=210)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_meal', models.CharField(max_length=210)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('courier', models.BooleanField()),
                ('customer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('mass_of_meal', models.IntegerField()),
                ('image_of_meal', models.ImageField(upload_to='ckeditor')),
                ('consist', models.TextField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ManyToManyField(to='survey.Currency')),
                ('type_of_cuisine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.cuisine')),
                ('type_of_meal', models.ManyToManyField(to='survey.Meal')),
                ('unit_of_measurement', models.ManyToManyField(to='survey.Unit')),
            ],
        ),
    ]
