# Generated by Django 3.1.1 on 2022-03-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type_of_cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.cuisine'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('what_food_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.dish')),
            ],
        ),
    ]
