# Generated by Django 3.1.1 on 2022-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20220321_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
