# Generated by Django 3.1.1 on 2022-03-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_comment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit2', models.CharField(max_length=50)),
            ],
        ),
    ]
