# Generated by Django 3.1.1 on 2022-03-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_unit2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit2',
        ),
    ]
