# Generated by Django 3.1.1 on 2022-03-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_delete_unit2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type_of_cuisine',
            field=models.ForeignKey(default='Японская кухня', on_delete=django.db.models.deletion.CASCADE, to='survey.cuisine'),
        ),
    ]
