# Generated by Django 3.1.1 on 2022-03-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20220325_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type_of_cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.cuisine'),
        ),
    ]
