# Generated by Django 3.1.1 on 2022-03-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20220325_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='name_of_restaurant',
            field=models.ManyToManyField(to='survey.Restaurant'),
        ),
    ]
