# Generated by Django 3.1.1 on 2022-03-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20220325_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='name_of_restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
