# Generated by Django 3.1.1 on 2022-03-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20220326_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type_of_cuisine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.cuisine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='type_of_cuisine',
            field=models.CharField(default='', max_length=210),
        ),
    ]
