# Generated by Django 3.1.1 on 2022-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20220326_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='employer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
