# Generated by Django 3.1.1 on 2022-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20220409_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, default='ckeditor/e_admin/no-image.jpg', upload_to='ckeditor'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
