# Generated by Django 3.1.1 on 2022-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20220409_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeradminauth',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
