# Generated by Django 3.1.1 on 2022-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20220410_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeradminauth',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
