# Generated by Django 3.1.1 on 2022-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20220410_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeradminauth',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='identifier',
            field=models.CharField(default='', max_length=200),
        ),
    ]
