# Generated by Django 3.1.1 on 2022-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20220410_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
