# Generated by Django 3.1.1 on 2022-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20220412_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='name_of_restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='type_of_cuisine',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
