# Generated by Django 3.1.1 on 2022-04-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20220413_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=200)),
                ('image_of_restaurant', models.ImageField(blank=True, default='ckeditor/e_admin/no-image.jpg', upload_to='ckeditor')),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('type_of_cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.cuisine')),
            ],
        ),
    ]
