# Generated by Django 3.1.1 on 2022-04-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20220413_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='names_of_restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.restaurant'),
            preserve_default=False,
        ),
    ]
