# Generated by Django 3.1.1 on 2022-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_dish_names_of_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, default='ckeditor/e_admin/', upload_to='ckeditor'),
        ),
    ]
