# Generated by Django 3.1.1 on 2022-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20220414_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, upload_to='ckeditor/e_admin'),
        ),
    ]
