# Generated by Django 3.1.1 on 2022-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20220414_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='consist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
