# Generated by Django 3.1.1 on 2022-04-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_auto_20220415_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type_of_meal',
        ),
        migrations.AddField(
            model_name='dish',
            name='type_of_meal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.meal'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dish',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='dish',
            name='unit_of_measurement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.unit'),
            preserve_default=False,
        ),
    ]
