# Generated by Django 3.1.1 on 2022-04-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_auto_20220420_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='IM',
            new_name='IN',
        ),
    ]
