# Generated by Django 3.1.1 on 2022-05-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='id_session',
            field=models.CharField(default='', max_length=200),
        ),
    ]
