# Generated by Django 3.1.1 on 2022-05-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_auto_20220518_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
    ]
