# Generated by Django 3.1.1 on 2022-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20220519_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image_of_meal',
            field=models.ImageField(default='', upload_to='ckeditor'),
        ),
    ]
