# Generated by Django 3.1.1 on 2022-05-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_basket_image_of_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price_for_one',
            field=models.IntegerField(default=0),
        ),
    ]
