# Generated by Django 3.1.1 on 2022-06-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0051_auto_20220614_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address_of_restaurant',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
