# Generated by Django 3.1.1 on 2022-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_auto_20220627_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, default='transparent-designer-must-have-fake-background-39672616.jpg', null=True, upload_to='ckeditor'),
        ),
    ]
