# Generated by Django 3.1.1 on 2022-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0056_auto_20220627_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='ckeditor'),
        ),
    ]
