# Generated by Django 3.1.1 on 2022-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_auto_20220627_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_of_restaurant',
            field=models.ImageField(blank=True, null=True, upload_to='ckeditor'),
        ),
    ]
