# Generated by Django 3.1.1 on 2022-06-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_auto_20220627_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_of_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_changed', models.DateTimeField(auto_now=True)),
                ('what_restaurant_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.restaurant')),
            ],
        ),
    ]
