# Generated by Django 4.0.5 on 2022-07-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0061_comment_of_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(default='', max_length=200)),
                ('id_product', models.CharField(default='', max_length=200)),
                ('id_customer', models.CharField(default='', max_length=200)),
                ('name_of_dish', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('col', models.PositiveBigIntegerField(default=0)),
                ('image_of_meal', models.ImageField(default='', upload_to='ckeditor')),
                ('price_for_one', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.currency')),
            ],
        ),
    ]
